# Default values for github-actions-kube-runner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  imageName: your_github-self-host-runner
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

resources:
  limits:
    cpu: 3000m
    memory: 500Mi
  requests:
    cpu: 3000m
    memory: 500Mi

projects:
  - name: repository_name1
    reponame: github_user_or_org/repository_name1
  - name: repository_name2
    reponame: github_user_or_org/repository_name2
